_products:
    path:     /
    defaults: { _controller: AppProductsBundle:Products:index }

_service_get_product:
    pattern:  /service/get_product/{id}
    defaults: { _controller: AppProductsBundle:Service:readProduct, _format: ~ }
    requirements:
        _method: GET
        id: "\d+"

_service_add_photo:
    pattern:  /service/add_photo/
    defaults: { _controller: AppProductsBundle:Service:addPhoto, _format: ~ }
    requirements:
        _method: POST


_service_remove_photo:
    pattern:  /service/remove_photo/
    defaults: { _controller: AppProductsBundle:Service:removePhoto, _format: ~ }
    requirements:
        _method: POST